"""
DO NOT EDIT!

This file is automatically @generated by blackjack.
"""
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def cargo_dependencies():


    http_archive(
        name = "blackjack_crates_io_cargo_lock",
        url = "https://crates.io/api/v1/crates/cargo-lock/6.0.1/download",
        sha256 = "e6f16e7adc20969298b1e137ac21ab3a7e7a9412fec71f963ff2fdc41663d70f",
        strip_prefix = "cargo-lock-6.0.1",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "cargo_lock",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_semver_0.11.0//:semver", "@blackjack_crates_io_serde//:serde", "@blackjack_crates_io_toml_0.5.6//:toml", "@blackjack_crates_io_url_2.1.1//:url"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_cargo_platform_0.1.1",
        url = "https://crates.io/api/v1/crates/cargo-platform/0.1.1/download",
        sha256 = "0226944a63d1bf35a3b5f948dd7c59e263db83695c9e8bffc4037de02e30f1d7",
        strip_prefix = "cargo-platform-0.1.1",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "cargo_platform",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_serde//:serde"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_cargo_metadata",
        url = "https://crates.io/api/v1/crates/cargo_metadata/0.12.3/download",
        sha256 = "7714a157da7991e23d90686b9524b9e12e0407a108647f52e9328f4b3d51ac7f",
        strip_prefix = "cargo_metadata-0.12.3",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "cargo_metadata",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_cargo_platform_0.1.1//:cargo_platform", "@blackjack_crates_io_semver_0.11.0//:semver", "@blackjack_crates_io_semver_parser_0.10.2//:semver_parser", "@blackjack_crates_io_serde//:serde", "@blackjack_crates_io_serde_json//:serde_json"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_cfg_expr",
        url = "https://crates.io/api/v1/crates/cfg-expr/0.7.1/download",
        sha256 = "2b81b9640fc656040fbf0d3f2bafacadcf17d55f2b0dc89589c1b80b0658fd5a",
        strip_prefix = "cfg-expr-0.7.1",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "cfg_expr",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_smallvec_1.6.1//:smallvec"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_idna_0.2.0",
        url = "https://crates.io/api/v1/crates/idna/0.2.0/download",
        sha256 = "02e2673c30ee86b5b96a9cb52ad15718aa1f966f5ab9ad54a8b95d5ca33120a9",
        strip_prefix = "idna-0.2.0",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "idna",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_matches_0.1.8//:matches", "@blackjack_crates_io_unicode_bidi_0.3.4//:unicode_bidi", "@blackjack_crates_io_unicode_normalization_0.1.13//:unicode_normalization"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_itoa_0.4.6",
        url = "https://crates.io/api/v1/crates/itoa/0.4.6/download",
        sha256 = "dc6f3ad7b9d11a0c00842ff8de1b60ee58661048eb8049ed33c73594f359d7e6",
        strip_prefix = "itoa-0.4.6",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "itoa",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_matches_0.1.8",
        url = "https://crates.io/api/v1/crates/matches/0.1.8/download",
        sha256 = "7ffc5c5338469d4d3ea17d269fa8ea3512ad247247c30bd2df69e68309ed0a08",
        strip_prefix = "matches-0.1.8",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "matches",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_percent_encoding_2.1.0",
        url = "https://crates.io/api/v1/crates/percent-encoding/2.1.0/download",
        sha256 = "d4fd5641d01c8f18a23da7b6fe29298ff4b55afcccdf78973b24cf3175fee32e",
        strip_prefix = "percent-encoding-2.1.0",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "percent_encoding",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_pest_2.1.3",
        url = "https://crates.io/api/v1/crates/pest/2.1.3/download",
        sha256 = "10f4872ae94d7b90ae48754df22fd42ad52ce740b8f370b03da4835417403e53",
        strip_prefix = "pest-2.1.3",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "pest",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_ucd_trie_0.1.3//:ucd_trie"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_proc_macro2_1.0.18",
        url = "https://crates.io/api/v1/crates/proc-macro2/1.0.18/download",
        sha256 = "beae6331a816b1f65d04c45b078fd8e6c93e8071771f41b8163255bbd8d7c8fa",
        strip_prefix = "proc-macro2-1.0.18",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "proc_macro2",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_unicode_xid_0.2.0//:unicode_xid"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "proc-macro"],
    rustc_flags = ["--cap-lints=allow"] + ["--cfg=use_proc_macro"],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_quote_1.0.7",
        url = "https://crates.io/api/v1/crates/quote/1.0.7/download",
        sha256 = "aa563d17ecb180e500da1cfd2b028310ac758de548efdd203e18f283af693f37",
        strip_prefix = "quote-1.0.7",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "quote",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_proc_macro2_1.0.18//:proc_macro2"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "proc-macro"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_ryu_1.0.5",
        url = "https://crates.io/api/v1/crates/ryu/1.0.5/download",
        sha256 = "71d301d4193d031abdd79ff7e3dd721168a9572ef3fe51a1517aba235bd8f86e",
        strip_prefix = "ryu-1.0.5",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "ryu",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = [],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_semver_0.11.0",
        url = "https://crates.io/api/v1/crates/semver/0.11.0/download",
        sha256 = "f301af10236f6df4160f7c3f04eec6dbc70ace82d23326abad5edee88801c6b6",
        strip_prefix = "semver-0.11.0",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "semver",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_semver_parser_0.10.2//:semver_parser", "@blackjack_crates_io_serde//:serde"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = ["default", "serde"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_semver_parser_0.10.2",
        url = "https://crates.io/api/v1/crates/semver-parser/0.10.2/download",
        sha256 = "00b0bef5b7f9e0df16536d3961cfb6e84331c065b4066afb39768d0e319411f7",
        strip_prefix = "semver-parser-0.10.2",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "semver_parser",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_pest_2.1.3//:pest"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_serde",
        url = "https://crates.io/api/v1/crates/serde/1.0.113/download",
        sha256 = "6135c78461981c79497158ef777264c51d9d0f4f3fc3a4d22b915900e42dac6a",
        strip_prefix = "serde-1.0.113",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "serde",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = [],
    proc_macro_deps = ["@blackjack_crates_io_serde_derive_1.0.113//:serde_derive"],
    edition = "2015",
    crate_features = ["default", "derive", "serde_derive", "std"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_serde_derive_1.0.113",
        url = "https://crates.io/api/v1/crates/serde_derive/1.0.113/download",
        sha256 = "93c5eaa17d0954cb481cdcfffe9d84fcfa7a1a9f2349271e678677be4c26ae31",
        strip_prefix = "serde_derive-1.0.113",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_proc_macro")

rust_proc_macro(
    name = "serde_derive",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_proc_macro2_1.0.18//:proc_macro2", "@blackjack_crates_io_quote_1.0.7//:quote", "@blackjack_crates_io_syn_1.0.32//:syn"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_serde_json",
        url = "https://crates.io/api/v1/crates/serde_json/1.0.62/download",
        sha256 = "ea1c6153794552ea7cf7cf63b1231a25de00ec90db326ba6264440fa08e31486",
        strip_prefix = "serde_json-1.0.62",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "serde_json",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_itoa_0.4.6//:itoa", "@blackjack_crates_io_ryu_1.0.5//:ryu", "@blackjack_crates_io_serde//:serde"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "std", "unbounded_depth"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_smallvec_1.6.1",
        url = "https://crates.io/api/v1/crates/smallvec/1.6.1/download",
        sha256 = "fe0f37c9e8f3c5a4a66ad655a93c74daac4ad00c441533bf5c6e7990bb42604e",
        strip_prefix = "smallvec-1.6.1",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "smallvec",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = [],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_syn_1.0.32",
        url = "https://crates.io/api/v1/crates/syn/1.0.32/download",
        sha256 = "a994520748611c17d163e81b6c4a4b13d11b7f63884362ab2efac3aa9cf16d00",
        strip_prefix = "syn-1.0.32",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "syn",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_proc_macro2_1.0.18//:proc_macro2", "@blackjack_crates_io_quote_1.0.7//:quote", "@blackjack_crates_io_unicode_xid_0.2.0//:unicode_xid"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["clone-impls", "default", "derive", "parsing", "printing", "proc-macro", "quote", "visit"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_tinyvec_0.3.4",
        url = "https://crates.io/api/v1/crates/tinyvec/0.3.4/download",
        sha256 = "238ce071d267c5710f9d31451efec16c5ee22de34df17cc05e56cbc92e967117",
        strip_prefix = "tinyvec-0.3.4",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "tinyvec",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = [],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["alloc", "default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_toml_0.5.6",
        url = "https://crates.io/api/v1/crates/toml/0.5.6/download",
        sha256 = "ffc92d160b1eef40665be3a05630d003936a3bc7da7421277846c2613e92c71a",
        strip_prefix = "toml-0.5.6",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "toml",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_serde//:serde"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_ucd_trie_0.1.3",
        url = "https://crates.io/api/v1/crates/ucd-trie/0.1.3/download",
        sha256 = "56dee185309b50d1f11bfedef0fe6d036842e3fb77413abef29f8f8d1c5d4c1c",
        strip_prefix = "ucd-trie-0.1.3",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "ucd_trie",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = [],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "std"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_unicode_bidi_0.3.4",
        url = "https://crates.io/api/v1/crates/unicode-bidi/0.3.4/download",
        sha256 = "49f2bd0c6468a8230e1db229cff8029217cf623c767ea5d60bfbd42729ea54d5",
        strip_prefix = "unicode-bidi-0.3.4",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "unicode_bidi",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_matches_0.1.8//:matches"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_unicode_normalization_0.1.13",
        url = "https://crates.io/api/v1/crates/unicode-normalization/0.1.13/download",
        sha256 = "6fb19cf769fa8c6a80a162df694621ebeb4dafb606470b2b2fce0be40a98a977",
        strip_prefix = "unicode-normalization-0.1.13",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "unicode_normalization",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_tinyvec_0.3.4//:tinyvec"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "std"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_unicode_xid_0.2.0",
        url = "https://crates.io/api/v1/crates/unicode-xid/0.2.0/download",
        sha256 = "826e7639553986605ec5979c7dd957c7895e93eabed50ab2ffa7f6128a75097c",
        strip_prefix = "unicode-xid-0.2.0",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "unicode_xid",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_url_2.1.1",
        url = "https://crates.io/api/v1/crates/url/2.1.1/download",
        sha256 = "829d4a8476c35c9bf0bbce5a3b23f4106f79728039b726d292bb93bc106787cb",
        strip_prefix = "url-2.1.1",
        type = "tar.gz",
        build_file_content = """
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "url",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    deps = ["@blackjack_crates_io_idna_0.2.0//:idna", "@blackjack_crates_io_matches_0.1.8//:matches", "@blackjack_crates_io_percent_encoding_2.1.0//:percent_encoding"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    
