"""
DO NOT EDIT!

This file is automatically @generated by blackjack.
"""
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def cargo_dependencies():


    http_archive(
        name = "blackjack_crates_io_autocfg_1.0.1",
        url = "https://crates.io/api/v1/crates/autocfg/1.0.1/download",
        sha256 = "cdb031dd78e28731d87d56cc8ffef4a8f36ca26c38fe2de700543e627f8a464a",
        strip_prefix = "autocfg-1.0.1",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "autocfg",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_cargo_lock",
        url = "https://crates.io/api/v1/crates/cargo-lock/4.0.1/download",
        sha256 = "8504b63dd1249fd1745b7b4ef9b6f7b107ddeb3c95370043c7dbcc38653a2679",
        strip_prefix = "cargo-lock-4.0.1",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "cargo_lock",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_gumdrop_0.7.0//:gumdrop", "@blackjack_crates_io_petgraph_0.5.1//:petgraph", "@blackjack_crates_io_semver_0.9.0//:semver", "@blackjack_crates_io_serde//:serde", "@blackjack_crates_io_toml_0.5.6//:toml", "@blackjack_crates_io_url_2.1.1//:url"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["cli", "default", "dependency-tree", "gumdrop", "petgraph"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_cargo_metadata",
        url = "https://crates.io/api/v1/crates/cargo_metadata/0.10.0/download",
        sha256 = "b8de60b887edf6d74370fc8eb177040da4847d971d6234c7b13a6da324ef0caf",
        strip_prefix = "cargo_metadata-0.10.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "cargo_metadata",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_semver_0.9.0//:semver", "@blackjack_crates_io_serde//:serde", "@blackjack_crates_io_serde_json//:serde_json"],
    proc_macro_deps = ["@blackjack_crates_io_serde_derive_1.0.113//:serde_derive"],
    edition = "2015",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_fixedbitset_0.2.0",
        url = "https://crates.io/api/v1/crates/fixedbitset/0.2.0/download",
        sha256 = "37ab347416e802de484e4d03c7316c48f1ecb56574dfd4a46a80f173ce1de04d",
        strip_prefix = "fixedbitset-0.2.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "fixedbitset",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_gumdrop_0.7.0",
        url = "https://crates.io/api/v1/crates/gumdrop/0.7.0/download",
        sha256 = "ee50908bc1beeac1f2902e0b4e0cd0d844e716f5ebdc6f0cfc1163fe5e10bcde",
        strip_prefix = "gumdrop-0.7.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "gumdrop",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = ["@blackjack_crates_io_gumdrop_derive_0.7.0//:gumdrop_derive"],
    edition = "2018",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_gumdrop_derive_0.7.0",
        url = "https://crates.io/api/v1/crates/gumdrop_derive/0.7.0/download",
        sha256 = "90454ce4de40b7ca6a8968b5ef367bdab48413962588d0d2b1638d60090c35d7",
        strip_prefix = "gumdrop_derive-0.7.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "gumdrop_derive",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "proc-macro",
    deps = ["@blackjack_crates_io_proc_macro2_1.0.18//:proc_macro2", "@blackjack_crates_io_quote_1.0.7//:quote", "@blackjack_crates_io_syn_1.0.32//:syn"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_hashbrown_0.8.2",
        url = "https://crates.io/api/v1/crates/hashbrown/0.8.2/download",
        sha256 = "e91b62f79061a0bc2e046024cb7ba44b08419ed238ecbd9adbd787434b9e8c25",
        strip_prefix = "hashbrown-0.8.2",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "hashbrown",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["raw"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_idna_0.2.0",
        url = "https://crates.io/api/v1/crates/idna/0.2.0/download",
        sha256 = "02e2673c30ee86b5b96a9cb52ad15718aa1f966f5ab9ad54a8b95d5ca33120a9",
        strip_prefix = "idna-0.2.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "idna",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_matches_0.1.8//:matches", "@blackjack_crates_io_unicode_bidi_0.3.4//:unicode_bidi", "@blackjack_crates_io_unicode_normalization_0.1.13//:unicode_normalization"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_indexmap_1.5.1",
        url = "https://crates.io/api/v1/crates/indexmap/1.5.1/download",
        sha256 = "86b45e59b16c76b11bf9738fd5d38879d3bd28ad292d7b313608becb17ae2df9",
        strip_prefix = "indexmap-1.5.1",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "indexmap",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_hashbrown_0.8.2//:hashbrown"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + ["--cfg=has_std"],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_itoa_0.4.6",
        url = "https://crates.io/api/v1/crates/itoa/0.4.6/download",
        sha256 = "dc6f3ad7b9d11a0c00842ff8de1b60ee58661048eb8049ed33c73594f359d7e6",
        strip_prefix = "itoa-0.4.6",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "itoa",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_matches_0.1.8",
        url = "https://crates.io/api/v1/crates/matches/0.1.8/download",
        sha256 = "7ffc5c5338469d4d3ea17d269fa8ea3512ad247247c30bd2df69e68309ed0a08",
        strip_prefix = "matches-0.1.8",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "matches",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_percent_encoding_2.1.0",
        url = "https://crates.io/api/v1/crates/percent-encoding/2.1.0/download",
        sha256 = "d4fd5641d01c8f18a23da7b6fe29298ff4b55afcccdf78973b24cf3175fee32e",
        strip_prefix = "percent-encoding-2.1.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "percent_encoding",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_petgraph_0.5.1",
        url = "https://crates.io/api/v1/crates/petgraph/0.5.1/download",
        sha256 = "467d164a6de56270bd7c4d070df81d07beace25012d5103ced4e9ff08d6afdb7",
        strip_prefix = "petgraph-0.5.1",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "petgraph",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_fixedbitset_0.2.0//:fixedbitset", "@blackjack_crates_io_indexmap_1.5.1//:indexmap"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "graphmap", "matrix_graph", "stable_graph"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_pico_args",
        url = "https://crates.io/api/v1/crates/pico-args/0.3.4/download",
        sha256 = "28b9b4df73455c861d7cbf8be42f01d3b373ed7f02e378d55fa84eafc6f638b1",
        strip_prefix = "pico-args-0.3.4",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "pico_args",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "eq-separator"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_proc_macro2_1.0.18",
        url = "https://crates.io/api/v1/crates/proc-macro2/1.0.18/download",
        sha256 = "beae6331a816b1f65d04c45b078fd8e6c93e8071771f41b8163255bbd8d7c8fa",
        strip_prefix = "proc-macro2-1.0.18",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "proc_macro2",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_unicode_xid_0.2.0//:unicode_xid"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "proc-macro"],
    rustc_flags = ["--cap-lints=allow"] + ["--cfg=use_proc_macro"],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_quote_1.0.7",
        url = "https://crates.io/api/v1/crates/quote/1.0.7/download",
        sha256 = "aa563d17ecb180e500da1cfd2b028310ac758de548efdd203e18f283af693f37",
        strip_prefix = "quote-1.0.7",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "quote",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_proc_macro2_1.0.18//:proc_macro2"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "proc-macro"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_ryu_1.0.5",
        url = "https://crates.io/api/v1/crates/ryu/1.0.5/download",
        sha256 = "71d301d4193d031abdd79ff7e3dd721168a9572ef3fe51a1517aba235bd8f86e",
        strip_prefix = "ryu-1.0.5",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "ryu",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_semver_0.9.0",
        url = "https://crates.io/api/v1/crates/semver/0.9.0/download",
        sha256 = "1d7eb9ef2c18661902cc47e535f9bc51b78acd254da71d375c2f6720d9a40403",
        strip_prefix = "semver-0.9.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "semver",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_semver_parser_0.7.0//:semver_parser", "@blackjack_crates_io_serde//:serde"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = ["default", "serde"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_semver_parser_0.7.0",
        url = "https://crates.io/api/v1/crates/semver-parser/0.7.0/download",
        sha256 = "388a1df253eca08550bef6c72392cfe7c30914bf41df5269b68cbd6ff8f570a3",
        strip_prefix = "semver-parser-0.7.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "semver_parser",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_serde",
        url = "https://crates.io/api/v1/crates/serde/1.0.113/download",
        sha256 = "6135c78461981c79497158ef777264c51d9d0f4f3fc3a4d22b915900e42dac6a",
        strip_prefix = "serde-1.0.113",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "serde",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = ["@blackjack_crates_io_serde_derive_1.0.113//:serde_derive"],
    edition = "2015",
    crate_features = ["default", "derive", "serde_derive", "std"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_serde_derive_1.0.113",
        url = "https://crates.io/api/v1/crates/serde_derive/1.0.113/download",
        sha256 = "93c5eaa17d0954cb481cdcfffe9d84fcfa7a1a9f2349271e678677be4c26ae31",
        strip_prefix = "serde_derive-1.0.113",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "serde_derive",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "proc-macro",
    deps = ["@blackjack_crates_io_proc_macro2_1.0.18//:proc_macro2", "@blackjack_crates_io_quote_1.0.7//:quote", "@blackjack_crates_io_syn_1.0.32//:syn"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_serde_json",
        url = "https://crates.io/api/v1/crates/serde_json/1.0.55/download",
        sha256 = "ec2c5d7e739bc07a3e73381a39d61fdb5f671c60c1df26a130690665803d8226",
        strip_prefix = "serde_json-1.0.55",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "serde_json",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_itoa_0.4.6//:itoa", "@blackjack_crates_io_ryu_1.0.5//:ryu", "@blackjack_crates_io_serde//:serde"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "std"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_syn_1.0.32",
        url = "https://crates.io/api/v1/crates/syn/1.0.32/download",
        sha256 = "a994520748611c17d163e81b6c4a4b13d11b7f63884362ab2efac3aa9cf16d00",
        strip_prefix = "syn-1.0.32",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "syn",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_proc_macro2_1.0.18//:proc_macro2", "@blackjack_crates_io_quote_1.0.7//:quote", "@blackjack_crates_io_unicode_xid_0.2.0//:unicode_xid"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["clone-impls", "default", "derive", "parsing", "printing", "proc-macro", "quote", "visit"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_tinyvec_0.3.4",
        url = "https://crates.io/api/v1/crates/tinyvec/0.3.4/download",
        sha256 = "238ce071d267c5710f9d31451efec16c5ee22de34df17cc05e56cbc92e967117",
        strip_prefix = "tinyvec-0.3.4",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "tinyvec",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["alloc", "default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_toml_0.5.6",
        url = "https://crates.io/api/v1/crates/toml/0.5.6/download",
        sha256 = "ffc92d160b1eef40665be3a05630d003936a3bc7da7421277846c2613e92c71a",
        strip_prefix = "toml-0.5.6",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "toml",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_serde//:serde"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_unicode_bidi_0.3.4",
        url = "https://crates.io/api/v1/crates/unicode-bidi/0.3.4/download",
        sha256 = "49f2bd0c6468a8230e1db229cff8029217cf623c767ea5d60bfbd42729ea54d5",
        strip_prefix = "unicode-bidi-0.3.4",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "unicode_bidi",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_matches_0.1.8//:matches"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_unicode_normalization_0.1.13",
        url = "https://crates.io/api/v1/crates/unicode-normalization/0.1.13/download",
        sha256 = "6fb19cf769fa8c6a80a162df694621ebeb4dafb606470b2b2fce0be40a98a977",
        strip_prefix = "unicode-normalization-0.1.13",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "unicode_normalization",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_tinyvec_0.3.4//:tinyvec"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "std"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_unicode_xid_0.2.0",
        url = "https://crates.io/api/v1/crates/unicode-xid/0.2.0/download",
        sha256 = "826e7639553986605ec5979c7dd957c7895e93eabed50ab2ffa7f6128a75097c",
        strip_prefix = "unicode-xid-0.2.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "unicode_xid",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_url_2.1.1",
        url = "https://crates.io/api/v1/crates/url/2.1.1/download",
        sha256 = "829d4a8476c35c9bf0bbce5a3b23f4106f79728039b726d292bb93bc106787cb",
        strip_prefix = "url-2.1.1",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "url",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_idna_0.2.0//:idna", "@blackjack_crates_io_matches_0.1.8//:matches", "@blackjack_crates_io_percent_encoding_2.1.0//:percent_encoding"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    
