"""
DO NOT EDIT!

This file is automatically generated by blackjack.
"""
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def cargo_dependencies():


    http_archive(
        name = "blackjack_crates_io_cargo_metadata",
        url = "https://crates.io/api/v1/crates/cargo_metadata/0.10.0/download",
        strip_prefix = "cargo_metadata-0.10.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "cargo_metadata",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_semver_0.9.0//:semver", "@blackjack_crates_io_serde//:serde", "@blackjack_crates_io_serde_json//:serde_json"],
    proc_macro_deps = ["@blackjack_crates_io_serde_derive_1.0.113//:serde_derive"],
    edition = "2015",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_itoa_0.4.6",
        url = "https://crates.io/api/v1/crates/itoa/0.4.6/download",
        strip_prefix = "itoa-0.4.6",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "itoa",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_proc_macro2_1.0.18",
        url = "https://crates.io/api/v1/crates/proc-macro2/1.0.18/download",
        strip_prefix = "proc-macro2-1.0.18",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "proc_macro2",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_unicode_xid_0.2.0//:unicode_xid"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "proc-macro"],
    rustc_flags = ["--cap-lints=allow"] + ["--cfg=use_proc_macro"],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_quote_1.0.7",
        url = "https://crates.io/api/v1/crates/quote/1.0.7/download",
        strip_prefix = "quote-1.0.7",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "quote",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_proc_macro2_1.0.18//:proc_macro2"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "proc-macro"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_ryu_1.0.5",
        url = "https://crates.io/api/v1/crates/ryu/1.0.5/download",
        strip_prefix = "ryu-1.0.5",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "ryu",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_semver_0.9.0",
        url = "https://crates.io/api/v1/crates/semver/0.9.0/download",
        strip_prefix = "semver-0.9.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "semver",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_semver_parser_0.7.0//:semver_parser", "@blackjack_crates_io_serde//:serde"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = ["default", "serde"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_semver_parser_0.7.0",
        url = "https://crates.io/api/v1/crates/semver-parser/0.7.0/download",
        strip_prefix = "semver-parser-0.7.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "semver_parser",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = [],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_serde",
        url = "https://crates.io/api/v1/crates/serde/1.0.113/download",
        strip_prefix = "serde-1.0.113",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "serde",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = ["@blackjack_crates_io_serde_derive_1.0.113//:serde_derive"],
    edition = "2015",
    crate_features = ["default", "derive", "serde_derive", "std"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_serde_derive_1.0.113",
        url = "https://crates.io/api/v1/crates/serde_derive/1.0.113/download",
        strip_prefix = "serde_derive-1.0.113",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "serde_derive",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "proc-macro",
    deps = ["@blackjack_crates_io_proc_macro2_1.0.18//:proc_macro2", "@blackjack_crates_io_quote_1.0.7//:quote", "@blackjack_crates_io_syn_1.0.32//:syn"],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_serde_json",
        url = "https://crates.io/api/v1/crates/serde_json/1.0.55/download",
        strip_prefix = "serde_json-1.0.55",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "serde_json",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_itoa_0.4.6//:itoa", "@blackjack_crates_io_ryu_1.0.5//:ryu", "@blackjack_crates_io_serde//:serde"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["default", "std"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_syn_1.0.32",
        url = "https://crates.io/api/v1/crates/syn/1.0.32/download",
        strip_prefix = "syn-1.0.32",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "syn",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = ["@blackjack_crates_io_proc_macro2_1.0.18//:proc_macro2", "@blackjack_crates_io_quote_1.0.7//:quote", "@blackjack_crates_io_unicode_xid_0.2.0//:unicode_xid"],
    proc_macro_deps = [],
    edition = "2018",
    crate_features = ["clone-impls", "default", "derive", "parsing", "printing", "proc-macro", "quote", "visit"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    

    http_archive(
        name = "blackjack_crates_io_unicode_xid_0.2.0",
        url = "https://crates.io/api/v1/crates/unicode-xid/0.2.0/download",
        strip_prefix = "unicode-xid-0.2.0",
        type = "tar.gz",
        build_file_content = """
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "unicode_xid",
    aliases = {},
    srcs = glob(["**/*.rs"]),
    crate_type = "lib",
    deps = [],
    proc_macro_deps = [],
    edition = "2015",
    crate_features = ["default"],
    rustc_flags = ["--cap-lints=allow"] + [],
    visibility = ["//visibility:public"],
)
    """,
    )
    
