load("@blackjack//:blackjack.bzl", "blackjack")

blackjack(name = "blackjack")

filegroup(
    name = "crates",
    srcs = [
        "@crates_io_actix_web//:actix_web",
        "@crates_io_diesel//:diesel",
    ],
)
